export const personalInfo = {
  name: "Avik Kumar Das",
  title: "Associate Professor | AI-ML Researcher | Signal Processing Expert",
  tagline: "Bridging Deep Technology with Real-World Impact",
  subTagline: "6 Years of Teaching · 60+ Publications · 14 Patents · IIT-backed Researcher",
  location: "Kolkata, India",
  email: "avikdas005@gmail.com",
  phone: "+91 9836820652",
  twitter: "@005avik_das",
  twitterUrl: "https://twitter.com/005avik_das",
  linkedin: "avikdasetc",
  linkedinUrl: "https://www.linkedin.com/in/avikdasetc",
  orcid: "https://orcid.org/0000-0001-8824-703X",
  bio: "PhD researcher at IIEST Shibpur and Associate Professor at UEM Kolkata, working at the frontier of Wireless Communication, Underwater Acoustics, LLMs, and IoT. With 14 patents and 60+ publications, I bridge cutting-edge research with real-world engineering impact. Recipient of PRISM (DSIR, Govt. of India) and MeitY TIDE Fund grants.",
};

export const heroStats = [
  { value: 6, label: "Years Experience", suffix: "" },
  { value: 60, label: "Publications", suffix: "+" },
  { value: 14, label: "Patents", suffix: "" },
  { value: 16, label: "Research Projects", suffix: "+" },
];

export const currentRole = {
  role: "Associate Professor",
  department: "CSE (IoT, CS & BT)",
  institution: "University of Engineering and Management (UEM Kolkata)",
  duration: "March 2024 – Present",
  badge: "Currently Active",
};

export const researchInterests = [
  {
    id: 1,
    title: "Wireless Communication & Signal Processing",
    description: "OTFS modulation, MIMO systems, and next-gen waveform design for high-mobility environments.",
    icon: "Radio",
    color: "from-blue-600 to-cyan-500",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur & UEM Kolkata", role: "Lead Researcher" },
    ],
  },
  {
    id: 2,
    title: "Underwater Acoustic Communication",
    description: "UAC channels, JANUS protocol, image & data transmission in underwater environments.",
    icon: "Waves",
    color: "from-cyan-600 to-blue-400",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur", role: "Primary Corresponding Author" },
      { name: "Prof. S. K. Mitra", email: "skmitra@etc.iiests.ac.in", affiliation: "IIEST Shibpur", role: "Co-Corresponding Author" },
    ],
  },
  {
    id: 3,
    title: "LLM / GPT / NLP & Deep Learning",
    description: "Large language models, natural language processing, and deep neural networks for intelligent systems.",
    icon: "Brain",
    color: "from-blue-500 to-violet-500",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Lead Investigator" },
    ],
  },
  {
    id: 4,
    title: "Internet of Things (IoT & IoUT)",
    description: "Smart sensor networks, IoT architectures, and Internet of Underwater Things.",
    icon: "Wifi",
    color: "from-sky-500 to-blue-600",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Primary Corresponding Author" },
    ],
  },
  {
    id: 5,
    title: "Visible Light Communication",
    description: "VLC systems for high-speed optical wireless communications and underwater environments.",
    icon: "Lightbulb",
    color: "from-blue-400 to-cyan-300",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur", role: "Lead Researcher" },
    ],
  },
  {
    id: 6,
    title: "Cognitive Radio Networks",
    description: "Dynamic spectrum access, cognitive radio technologies, and adaptive communication systems.",
    icon: "Activity",
    color: "from-indigo-600 to-blue-500",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Corresponding Author" },
    ],
  },
  {
    id: 7,
    title: "Underground Mine Monitoring",
    description: "LoRa, WSN-based positioning and safety monitoring systems for underground mines.",
    icon: "Mountain",
    color: "from-blue-700 to-cyan-600",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur", role: "Lead PI" },
    ],
  },
  {
    id: 8,
    title: "6G & Terahertz Communication",
    description: "Channel modeling, AI-driven terahertz communication, and next-generation 6G networks.",
    icon: "Zap",
    color: "from-cyan-500 to-sky-400",
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Lead Author" },
    ],
  },
];

export const experience = [
  {
    id: 1,
    role: "Associate Professor",
    department: "CSE (IoT, CS & BT)",
    institution: "University of Engineering and Management (UEM Kolkata)",
    duration: "March 2024 – Present",
    years: "2 Years",
    isCurrent: true,
    location: "Kolkata, WB",
  },
  {
    id: 2,
    role: "Visiting Professor",
    department: "Electronics & Communication",
    institution: "Calcutta University (CU)",
    duration: "Sept 2023 – Feb 2024",
    years: "6 Months",
    isCurrent: false,
    location: "Kolkata, WB",
  },
  {
    id: 3,
    role: "Honorary Researcher",
    department: "Digital System Design (DSD Research Lab)",
    institution: "IIEST Shibpur",
    duration: "Dec 2021 – January 2024",
    years: "2 Years",
    isCurrent: false,
    location: "Howrah, WB",
  },
  {
    id: 4,
    role: "Assistant Professor",
    department: "Electronics & Communication Engineering",
    institution: "Seacom Engineering College (MAKAUT/WBUT)",
    duration: "March 2017 – August 2018",
    years: "1.5 Years",
    isCurrent: false,
    location: "Howrah, WB",
  },
  {
    id: 5,
    role: "Examiner",
    department: "",
    institution: "West Bengal University of Technology (MAKAUT)",
    duration: "July 2017 – August 2018",
    years: "1 Year",
    isCurrent: false,
    location: "Kolkata, WB",
  },
  {
    id: 6,
    role: "IT Support Executive",
    department: "",
    institution: "Goldstar Technology, Kolkata",
    duration: "August 2012 – July 2014",
    years: "2 Years",
    isCurrent: false,
    location: "Kolkata, WB",
  },
];

export const education = [
  {
    id: 1,
    degree: "PhD",
    field: "Electronics & Telecommunication Engineering",
    institution: "IIEST, Shibpur, Howrah",
    duration: "2018 – Present",
    status: "Pre-submission completed 13.09.2023",
    grade: "",
    icon: "🎓",
  },
  {
    id: 2,
    degree: "M.Tech",
    field: "Information & Communication Engineering",
    institution: "IIEST, Shibpur, Howrah",
    duration: "June 2014 – May 2016",
    status: "Completed",
    grade: "CGPA: 60.67%",
    icon: "🎓",
  },
  {
    id: 3,
    degree: "B.Tech",
    field: "Electronics & Communication Engineering",
    institution: "West Bengal University of Technology",
    duration: "August 2008 – June 2012",
    status: "Completed",
    grade: "CGPA: 8.13",
    icon: "🎓",
  },
  {
    id: 4,
    degree: "Higher Secondary (10+2)",
    field: "Math, Physics, Chemistry, Biology",
    institution: "Rajbalhat High School (WBCHSE)",
    duration: "May 2007",
    status: "Completed",
    grade: "78.80%",
    icon: "🏫",
  },
];

export const publicationsStats = {
  total: "60+",
  patents: 14,
  patentsGranted: 2,
  patentsPublished: 2,
  patentsFiled: 10,
  journals: 10,
  ieeeTransactions: 2,
  bookChapters: 11,
  conferences: 37,
};

export const featuredPublications = [
  {
    id: 1,
    title: "Image Transmission in UWA Channel using CS based OTFS system",
    publisher: "Microsystem Technologies, Springer",
    year: "2023",
    type: "Journal",
    doi: "https://doi.org/10.1007/s00542-023-05500-w",
    pdfLink: "",
    description: "Proposed a novel compressive sensing (CS) based Orthogonal Time Frequency Space (OTFS) modulation scheme for reliable image transmission over highly dispersive underwater acoustic (UWA) channels.",
    authors: ["Avik Kumar Das", "S. K. Mitra", "A. Roy"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "Dept. of ETC, IIEST Shibpur", role: "Primary Corresponding Author" },
    ],
    keywords: ["Underwater Acoustic", "OTFS", "Compressive Sensing", "Image Transmission"],
  },
  {
    id: 2,
    title: "Convolution Neural Network for Sparse Channel and Image Reconstruction in Underwater Acoustic Communication",
    publisher: "Taylor & Francis",
    year: "2023",
    type: "Journal",
    doi: "",
    pdfLink: "",
    description: "Developed a CNN architecture specifically tailored for joint sparse channel estimation and image reconstruction in challenging underwater acoustic environments.",
    authors: ["Avik Kumar Das", "D. Sarkar", "S. K. Mitra"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur & UEM Kolkata", role: "Corresponding Author" },
    ],
    keywords: ["CNN", "Deep Learning", "Channel Estimation", "Underwater Communication"],
  },
  {
    id: 3,
    title: "Image Transmission in Underwater Acoustic Communication Channel using LDPC codes",
    publisher: "IEEE CODEC Conference",
    year: "2023",
    type: "Conference",
    doi: "",
    pdfLink: "",
    description: "Analyzed the performance of Low-Density Parity-Check (LDPC) codes in mitigating multipath fading and noise during image transmission through underwater acoustic channels.",
    authors: ["Avik Kumar Das", "P. Sengupta"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur", role: "Corresponding Author" },
    ],
    keywords: ["LDPC", "Error Correction", "UWA Channel", "Signal Processing"],
  },
  {
    id: 4,
    title: "Development of Automated Cardiac Arrhythmia Detection Methods Using Single Channel ECG Signal",
    publisher: "arXiv:2308.02405",
    year: "2023",
    type: "Preprint",
    doi: "https://arxiv.org/abs/2308.02405",
    pdfLink: "https://arxiv.org/pdf/2308.02405.pdf",
    description: "Presented an automated machine learning pipeline for robust cardiac arrhythmia detection using features extracted from single-channel ECG signals, achieving high diagnostic accuracy.",
    authors: ["Avik Kumar Das", "R. Banerjee"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Lead Author" },
    ],
    keywords: ["ECG", "Arrhythmia", "Machine Learning", "Biomedical Signal Processing"],
  },
  {
    id: 5,
    title: "Enhanced Stock Price Forecasting Using Hybrid Bidirectional LSTM-GRU Model",
    publisher: "IRTM 2024 (Accepted & Presented)",
    year: "2024",
    type: "Conference",
    doi: "",
    pdfLink: "",
    description: "Introduced a hybrid deep learning model combining Bidirectional LSTM and GRU networks to effectively capture long-term temporal dependencies for accurate stock market prediction.",
    authors: ["Avik Kumar Das", "S. Dutta"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Corresponding Author" },
    ],
    keywords: ["Time Series", "Bi-LSTM", "GRU", "Financial Forecasting"],
  },
  {
    id: 6,
    title: "Enhanced CNN for Sign Character Recognition with Mixed Pooling and Mish Activation",
    publisher: "ICISAA, IEEE Pune",
    year: "2024",
    type: "Conference",
    doi: "",
    pdfLink: "",
    description: "Designed an improved Convolutional Neural Network incorporating mixed pooling layers and Mish activation function to enhance the recognition rate of sign language characters.",
    authors: ["Avik Kumar Das", "M. K. Ghosh"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "Corresponding Author" },
    ],
    keywords: ["Computer Vision", "Sign Language", "CNN", "Mish Activation"],
  },
];

export const projects = [
  {
    id: 1,
    title: "AQUA-SENSE-AI",
    description: "Advanced Underwater Monitoring for Internet of Underwater Things (IoUT) with AI-powered sensing.",
    institution: "UEM Kolkata",
    duration: "Sept 2024 – Aug 2025",
    status: "Active",
    category: "IoT",
    funded: "PI",
    featured: true,
    authors: ["Dr. Avik Kumar Das", "Research Team UEM"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "Dept. of CSE, UEM Kolkata", role: "Principal Investigator & Corresponding Author" },
    ],
  },
  {
    id: 2,
    title: "GAPPS",
    description: "GNSS & AI-based Precision Positioning System for high-accuracy location tracking.",
    institution: "UEM Kolkata",
    duration: "Sept 2024 – Aug 2025",
    status: "Active",
    category: "GNSS",
    funded: "PI",
    featured: true,
    authors: ["Dr. Avik Kumar Das", "Precision Lab Team"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "UEM Kolkata", role: "PI & Lead Author" },
    ],
  },
  {
    id: 3,
    title: "Underwater VLC & UWA UUV Design",
    description: "Underwater Vehicle (UUV) with Visible Light Communication and Acoustic channels for deep exploration.",
    institution: "IIEST, Shibpur",
    duration: "2019 – Present",
    status: "Active",
    category: "Communication",
    funded: "",
    featured: true,
    authors: ["Dr. Avik Kumar Das", "DSD Research Lab"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "IIEST Shibpur", role: "Lead Investigator" },
    ],
  },
  {
    id: 4,
    title: "NLP & LLM Voice/Speech Processing",
    description: "Voice-based alerting system using NLP, LLM, and speech processing for intelligent automation.",
    institution: "Addauto Technology Pvt. Ltd.",
    duration: "2021 – Present",
    status: "Active",
    category: "AI/ML",
    funded: "",
    featured: true,
    authors: ["Dr. Avik Kumar Das", "Addauto AI Team"],
    correspondingAuthors: [
      { name: "Dr. Avik Kumar Das", email: "avikdas005@gmail.com", affiliation: "Addauto Tech & UEM Kolkata", role: "Corresponding Advisor" },
    ],
  },
  {
    id: 5,
    title: "IoT & LoRa Underground Mine Monitoring",
    description: "IBM-backed real-time monitoring and positioning system for underground mines using LoRa & WSN.",
    institution: "IIEST, Shibpur",
    duration: "2020 – Present",
    status: "Active",
    category: "IoT",
    funded: "IBM-backed",
    featured: false,
  },
  {
    id: 6,
    title: "Real-Time Visibility Enhancement",
    description: "PRISM-funded AI system for real-time image visibility enhancement in adverse conditions.",
    institution: "IIEST, Shibpur",
    duration: "2021 – Present",
    status: "Active",
    category: "AI/ML",
    funded: "PRISM",
    featured: false,
  },
  {
    id: 7,
    title: "TYGR: AI-Enabled Vehicle Tracking",
    description: "IoT & AI-enabled real-time vehicle tracking using GNSS for fleet management.",
    institution: "UEM Kolkata",
    duration: "Sept 2024 – Aug 2025",
    status: "Active",
    category: "GNSS",
    funded: "PI",
    featured: false,
  },
  {
    id: 8,
    title: "AI-PLANT-VISION",
    description: "AI-based plant disease monitoring and early detection system using computer vision.",
    institution: "UEM Kolkata",
    duration: "Sept 2024 – Aug 2025",
    status: "Active",
    category: "AI/ML",
    funded: "PI",
    featured: false,
  },
  {
    id: 9,
    title: "6G Channel Modeling & THz Communication",
    description: "AI-driven modeling of terahertz communication channels for next-generation 6G networks.",
    institution: "UEM Kolkata",
    duration: "January 2024 – Present",
    status: "Active",
    category: "Communication",
    funded: "",
    featured: false,
  },
  {
    id: 10,
    title: "IoT Water Quality Monitoring Node",
    description: "Floating IoT node with UV-based water quality monitoring and WPT-based docking station.",
    institution: "IIEST, Shibpur",
    duration: "2021 – Present",
    status: "Active",
    category: "IoT",
    funded: "",
    featured: false,
  },
];

export const awards = [
  {
    id: 1,
    title: "PRISM Funding",
    issuer: "DSIR, Govt. of India",
    via: "via IIT Kharagpur",
    year: "2024",
    icon: "🏆",
    highlight: true,
  },
  {
    id: 2,
    title: "MeitY TIDE Fund",
    issuer: "Govt. of India",
    via: "via SINE IIT Bombay",
    year: "2023",
    icon: "🏆",
    highlight: true,
  },
  {
    id: 3,
    title: "IEEE R10 WIE Hackathon Winner",
    issuer: "Smart Resource Management",
    via: "Jadavpur University",
    year: "2023",
    icon: "🥇",
    highlight: false,
  },
  {
    id: 4,
    title: "Top 3 Globally",
    issuer: "AEGIS GRAHAM BELL Award",
    via: "Smart Water Monitoring System",
    year: "2023",
    icon: "🌐",
    highlight: false,
  },
  {
    id: 5,
    title: "IIC Prototype Competition Funding",
    issuer: "IIEST, Shibpur",
    via: "",
    year: "2022 – Present",
    icon: "🔬",
    highlight: false,
  },
  {
    id: 6,
    title: "Official Photographer",
    issuer: "AJC Bose Indian Botanic Garden (BSI)",
    via: "",
    year: "2022 – Present",
    icon: "📸",
    highlight: false,
  },
  {
    id: 7,
    title: "Speaker — IoT & Embedded Systems Seminar",
    issuer: "BIT Techno India",
    via: "",
    year: "2023",
    icon: "🎤",
    highlight: false,
  },
];

export const technicalSkills = [
  { name: "Python", level: 85 },
  { name: "MATLAB", level: 78 },
  { name: "FPGA / LabVIEW", level: 68 },
  { name: "Arduino / ESP", level: 82 },
  { name: "LaTeX", level: 90 },
  { name: "R / SQL", level: 72 },
];

export const languages = [
  { name: "English", level: 5 },
  { name: "Bengali", level: 5 },
  { name: "Hindi", level: 5 },
  { name: "Sanskrit", level: 5 },
];

export const toolChips = [
  "Python", "MATLAB", "Arduino", "Raspberry Pi", "LaTeX",
  "Photoshop", "Eagle PCB", "LabVIEW", "RTKLib", "LattePanda",
  "ESP32", "FPGA", "TMS320C6748", "CCS", "C Programming",
];

export const identityBadges = [
  "PhD Researcher",
  "IEEE Member",
  "OSI Life Member",
  "IIT Shibpur Alumni",
  "14 Patent Holder",
  "Goalkeeper – IIEST",
  "BFA Musician",
  "Nature Photographer",
];

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Experience", href: "/#experience" },
  {label:"Team",href:"/team"},
  { label: "Projects", href: "/projects" },
  { label: "Publications", href: "/publications" },
  { label: "Awards", href: "/#awards" },
];
